// SPDX-License-Identifier: BUSL-1.1
pragma solidity ^0.8.28;

library Errors {
    error InvalidStaticsDollarRail();
    error MarketNotFound(bytes32 marketId);
    error InvalidAmount(uint256 amount);
    error ArrayLengthMismatch(uint256 expected, uint256 actual);
    error AveragePriceExceeded(uint128 averagePrice, uint128 maxAveragePrice);
    error CurveMarketMismatch(bytes32 expectedMarketId, bytes32 actualMarketId);
    error CurveBookMismatch(bytes32 expectedBookId, bytes32 actualBookId);
    error CurveSideMismatch(bool expectedYesSide, bool actualYesSide);
    error BookNotFound(bytes32 bookId);
    error BookAlreadyExists(bytes32 bookId);
    error BookNotActive(bytes32 bookId);
    error NotBookController(address caller, bytes32 bookId);
    error BookDecommissionUnsupported(bytes32 bookId);
    error BookNotDecommissionPending(bytes32 bookId);
    error BookDecommissionNotReady(bytes32 bookId, uint64 availableAt);
    error BookAssetTypeMismatch(bytes32 bookId, uint8 expected, uint8 actual);
    error UnsupportedBaseTransferMode(uint8 assetType, uint8 transferMode);
    error BaseTransferDeltaMismatch(address token, uint256 expected, uint256 actual);
    error SelfFillNotAllowed(uint256 curveId, address maker, address taker);
    error ComboMarketTokenMismatch(bytes32 marketId, address expectedPositionToken, address actualPositionToken);

    error InsufficientCreationFeeOrReserve();
    error InsufficientCreationBond();
    error InsufficientInitialLiquidityCollateral();
    error ExpiryTooSoon(uint64 expiryTime, uint64 minExpiry);
    error ExpiryTooLate(uint64 expiryTime, uint64 maxExpiry);
    error MarketAlreadyExists(bytes32 marketId);
    error CTFConditionPreparationFailed(bytes32 questionId);
    error PermissionlessCreationDisabled(address caller);
    error MetadataFieldTooLong(string fieldName, uint256 length, uint256 maxLength);
    error MetadataFieldRequired(string fieldName);
    error InvalidOutcomeCount(uint256 count);
    error DuplicateOutcomeLabel(uint256 firstIndex, uint256 duplicateIndex);
    error MarketGroupNotFound(bytes32 groupId);
    error MarketGroupAlreadyExists(bytes32 groupId);
    error DuplicateGroupMarket(bytes32 groupId, bytes32 marketId);
    error MultiOutcomeMarketNotFound(bytes32 marketId);
    error MultiOutcomeMarketResolved(bytes32 marketId);
    error MultiOutcomeMarketNotResolved(bytes32 marketId);
    error MissingCompleteOutcomeSet(bytes32 marketId, uint8 outcome, uint256 required, uint256 balance);

    error MarketNotTrading(bytes32 marketId);
    error InsufficientMakerEscrow(uint128 required, uint128 provided);
    error GenerationMismatch(uint32 expected, uint32 actual);
    error CommitmentMismatch(bytes32 expected, bytes32 actual);
    error SlippageExceeded(uint128 sharesOut, uint128 minSharesOut);
    error NotCurveOwner(address caller, address maker);
    error CurveNotActive(uint256 curveId);
    error CurveExpired(uint256 curveId);
    error CurveNotReusable(uint256 curveId, uint128 remainingVolume, uint64 expiresAt);
    error CurvePruneBatchTooLarge(uint256 length, uint256 maximum);
    error InvalidPageSize(uint256 size, uint256 maximum);
    error CurveBackingMismatch(uint256 curveId, uint8 expected, uint8 actual);
    error AdapterCurveMetadataMissing(uint256 curveId);
    error AdapterCurveInactive(uint256 curveId);
    error InvalidProductAdapter(uint8 adapterKind);
    error QuoteEnvelopeBoundToAdapterCurve(uint256 envelopeId, uint256 curveId);
    error InvalidProfileId(uint8 profileId);
    error InvalidTickPreset(uint8 tickPresetId);
    error InsufficientVolume(uint128 requested, uint128 remaining);
    error CurveTopUpVolumeMismatch(uint256 totalYesVolume, uint256 totalNoVolume);
    error PositionIdMismatch(uint256 expected, uint256 actual);
    error QuoteAmountMismatch(uint128 provided, uint128 required);
    error InsufficientCredit(
        address owner, uint8 creditAssetType, address token, uint256 tokenId, uint128 requested, uint128 available
    );
    error UnsupportedCreditAssetType(uint8 creditAssetType);
    error DelayedOrderNotFound(uint256 orderId);
    error UnsupportedDelayedOrderKind(uint8 kind);
    error UnsupportedDelayedOrderBook(bytes32 bookId);
    error DelayedOrderQueueEmpty(bytes32 bookId);
    error DelayedOrderRouteMismatch(uint256 orderId, bytes32 expected, bytes32 actual);
    error DelayedOrderRouteRequired(uint256 orderId);
    error DelayedOrderPaused();
    error DelayedOrderProcessorNotAllowed(address processor);
    error DelayedOrderRouteTooLong(uint256 length, uint256 maxLength);
    error DelayedOrderQuoteBelowMinimum(uint256 normalizedAmount, uint256 minimum);
    error DelayedOrderBaseBelowMinimum(uint256 normalizedAmount, uint256 minimum);
    error DelayedOrderHeadMismatch(bytes32 bookId, uint64 expectedHead, uint64 actualHead);

    error MarketNotPending(bytes32 marketId);
    error MarketNotDisputed(bytes32 marketId);
    error NotMarketCreator(address caller, address creator);
    error InvalidOutcome(uint8 outcome);
    error MarketNotExpired(bytes32 marketId);
    error MarketAlreadyResolved(bytes32 marketId);
    error DisputeWindowClosed(bytes32 marketId);
    error SameOutcome(uint8 proposed, uint8 counter);
    error InsufficientDisputeBond(uint128 required, uint128 provided);
    error InsufficientEveBond(uint128 required, uint128 provided);
    error ResolutionNotReady(bytes32 marketId);
    error NoActiveResolution(bytes32 marketId);
    error CreatorGraceActive(bytes32 marketId);
    error CreatorGraceExpired(bytes32 marketId);
    error OpenResolutionExpired(bytes32 marketId);
    error MarketNotResolved(bytes32 marketId);
    error PayoutsAlreadyReported(bytes32 marketId);
    error InvalidRedemptionParams(bytes32 marketId);
    error NotParimutuelMarket(bytes32 marketId);
    error NotCLOBMarket(bytes32 marketId);
    error PositionTokenTypeMismatch(bytes32 marketId, uint8 expected, uint8 actual);
    error NoWinningShares(bytes32 marketId, address user);
    error ParimutuelPoolNotFinalized(bytes32 marketId);
    error FeeExceedsAmount(uint128 amount, uint128 fee);
    error ClaimableSharesRemain(bytes32 marketId, uint256 remainingShares);
    error FeeSplitExceedsDenominator(uint16 creatorFeeBps, uint16 protocolFeeBps);
    error InvalidParimutuelEpochWindow(uint64 epochWindow, uint64 maxEpochWindow);
    error InvalidParimutuelEpochMultiplier(uint256 epoch, uint256 multiplierBps);
    error ParimutuelSharesWouldRoundToZero(bytes32 marketId, uint128 netCollateral, uint256 multiplierBps);

    error CreatorNotEligible(bytes32 marketId);
    error AlreadyClaimed(bytes32 marketId, address maker);
    error NoFeesAccrued(bytes32 marketId);

    error NoBondToReturn(bytes32 marketId, address user);
    error NoBondToSlash(bytes32 marketId, address user);
    error InvalidResolutionIndex(bytes32 marketId, uint256 proposalIndex);
    error InternalCallOnly(address caller);

    error IdentityAlreadyOwned(address owner);
    error IdentityNotFound(uint256 identityId);
    error NotIdentityOwner(address caller);
    error IdentityTransferDisabled();
    error IdentityApprovalDisabled();
    error MintFeeCollectionFailed();
    error NotResolverRole(uint256 identityId);
    error InsufficientResolverStake(uint128 required, uint128 actual);
    error ResolverNotActive(uint256 identityId);
    error CannotExitFromState(uint8 lifecycle);
    error StakeLocked(uint256 identityId);
    error ActivationDelayNotElapsed(uint256 identityId);
    error ResolverEpochClosed(uint64 epochId);
    error ResolverEpochNotReady(uint64 epochId);
    error ResolverEpochAlreadyFinalized(uint64 epochId);
    error ResolverEpochCandidateMissing(uint64 epochId, uint256 identityId);
    error ResolverEpochCandidateExists(uint64 epochId, uint256 identityId);
    error ResolverEpochCandidateIneligible(uint64 epochId, uint256 identityId);
    error ResolverEpochScoreSubmitted(uint64 epochId, uint256 identityId);
    error ResolverEpochUnderfilled(uint64 epochId, uint256 selected, uint256 required);
    error ResolverSetNotReady(uint256 activeCount, uint256 requiredCount);
    error ResolutionModeDisabled(uint8 mode);
    error InsufficientEpochRandomnessReveals(uint64 epochId);
    error InvalidCommitteeSize(uint16 committeeSize);
    error NotCommitteeMember(uint256 identityId);
    error CommitPhaseClosed(bytes32 disputeId);
    error RevealPhaseClosed(bytes32 disputeId);
    error AlreadyCommitted(uint256 identityId);
    error JuryCommitmentMismatch(uint256 identityId);
    error AlreadyRevealed(uint256 identityId);
    error InvalidJuryOutcome(uint8 outcome);
    error AppealWindowClosed(bytes32 disputeId);
    error AppealBondTooLow(uint128 required, uint128 provided);
    error MaxAppealRoundsReached(uint8 round);
    error DisputeAlreadyFinalized(bytes32 disputeId);
    error RewardsAlreadyDistributed(bytes32 disputeId);
    error InvalidRoutingSplit();
    error InvalidConfigValue(bytes32 paramName);
    error RandomnessNotReady(bytes32 disputeId);
    error InsufficientRandomnessReveals(bytes32 disputeId);
    error RandomnessFallbackUnavailable(bytes32 disputeId);

    error SelectorFrozen(bytes4 selector);
    error NotContractOwner(address caller);
    error ZeroAddress();
    error CollateralProfileNotFound(uint8 profileId);
    error CollateralProfileDisabled(uint8 profileId);
    error UnsupportedCollateralToken(address expectedCollateral, address actualCollateral);
    error InvalidFeeSplit(uint256 totalBps);
    error InvalidDurationBounds(uint64 minMarketDuration, uint64 maxMarketDuration);
    error ContractHasNoCode(address account);
    error InvalidContractInterface(address account, bytes4 selector);
    error FacetIsZero();
    error FacetHasNoCode(address facet);
    error SelectorsEmpty();
    error SelectorAlreadyExists(bytes4 selector);
    error SelectorMissing(bytes4 selector);
    error GovernanceDelayAlreadyFinalized();
    error GovernanceDelayNotFinalized();
    error GovernanceOperationAlreadyScheduled(bytes32 operationId, uint256 readyAt);
    error GovernanceOperationNotScheduled(bytes32 operationId);
    error GovernanceOperationTimelocked(bytes32 operationId, uint256 readyAt);
    error SelectorUnchanged(bytes4 selector, address facet);
    error InitCalldataWithoutInit();
    error InitHasNoCode(address init);
    error InitCalldataEmpty();
    error DiamondInitFailed();
    error SelectorNotOnFacet(bytes4 selector, address facet);
    error RemoveFacetMustBeZero(address facet);

    error ParlayNotConfigured();
    error ParlayTemplateNotFound(uint256 templateId);
    error ParlayTemplateAlreadyExists(uint256 templateId);
    error ParlayOfferNotFound(uint256 offerId);
    error ParlayRequestNotFound(uint256 requestId);
    error ParlayTicketNotFound(uint256 ticketId);
    error ParlayInactive(uint256 id);
    error ParlayExpired(uint256 id);
    error ParlayLegCountInvalid(uint256 count);
    error ParlayDuplicateMarket(bytes32 marketId);
    error ParlayNonCanonicalLegs(bytes32 previousMarketId, bytes32 currentMarketId);
    error ParlayMarketNotFillable(bytes32 marketId, uint8 state, uint8 outcome);
    error ParlayUnsupportedMarketType(bytes32 marketId, uint8 marketType);
    error ParlayCollateralMismatch(bytes32 marketId, address expectedCollateral, address actualCollateral);
    error ParlayUnsupportedOutcome(uint8 outcome);
    error ParlayInvalidPolicy(uint8 invalidPolicy);
    error ParlayInvalidPayoutTiers();
    error ParlayMaxPayoutMismatch(uint128 expected, uint128 actual);
    error ParlayNotFinalized(uint256 ticketId);
    error ParlayAlreadyFinalized(uint256 ticketId);
    error ParlayLegUnresolved(bytes32 marketId);
    error ParlayReceiverMismatch(address expected, address actual);
    error ParlayBudgetNotFound(uint256 budgetId);
    error ParlayBudgetInactive(uint256 budgetId);
    error ParlayBudgetWrongOwner(address caller, address owner);
    error ParlayBudgetWrongMode(uint8 expected, uint8 actual);
    error ParlayBudgetInsufficient(uint256 required, uint256 available);
    error ParlayBudgetCollateralProfileMismatch(uint256 budgetId, uint8 budgetProfileId, uint8 quoteProfileId);

    error NativePositionNotFound(uint256 positionId);
    error NativeCollateralTransferMismatch(address collateralToken, uint256 expected, uint256 received);
    error NativeCollateralLiabilityInsufficient(address collateralToken, uint256 available, uint256 required);
    error NativeCollateralBackingInsufficient(address collateralToken, uint256 balance, uint256 liability);
    error NativeConditionNotFound(bytes32 conditionId);
    error NativeModuleUnsupported(uint8 moduleId);
    error NativeOutcomeUnsupported(uint8 outcomeIndex);
    error NativeBinaryConditionNotFound(bytes32 marketId);
    error NativeNegRiskConditionNotFound(bytes32 marketId, uint8 excludedOutcome);
    error NativePositionConditionMismatch(uint256 positionId, bytes32 expectedConditionId, bytes32 actualConditionId);
    error EvesPositionManagerAlreadyConfigured(address currentManager);
    error EvesPositionManagerDiamondMismatch(address manager, address expectedDiamond, address actualDiamond);
    error NegRiskAdapterAlreadyConfigured(address currentAdapter);
    error NegRiskAdapterConfigMismatch(address adapter);

    error ComboConditionNotFound(bytes32 conditionId);
    error ComboLegCountInvalid(uint256 count);
    error ComboNonCanonicalLegs(uint256 previousPositionId, uint256 currentPositionId);
    error ComboDuplicateCondition(bytes32 conditionId);
    error ComboConflictingConditions(bytes32 firstConditionId, bytes32 secondConditionId);
    error ComboLegMarketNotStarted(bytes32 marketId);
    error ComboLegMarketResolved(bytes32 marketId);
    error ComboUnsupportedPosition(uint256 positionId);
    error ComboCTFEscrowInsufficient(uint256 positionId, uint256 available, uint256 required);
    error CTFSettlementAdapterAlreadyConfigured(address adapter);
    error ComboCollateralMismatch(address expectedCollateral, address actualCollateral);
    error ComboCollateralProfileMismatch(uint8 expectedProfileId, uint8 actualProfileId);
    error ComboPositionNotRedeemable(uint256 positionId);
    error ComboPositionNotCompressible(uint256 positionId);
    error ComboSingleLegRequired(uint256 legCount);
    error ComboConditionAlreadyPresent(bytes32 conditionId);
    error ComboParentYesRequired(uint256 positionId);
    error ComboNoPositionRequired(uint256 positionId);
    error ComboLegIndexOutOfRange(uint256 index, uint256 legCount);
    error ComboBasketPageInvalid(uint256 cursor, uint256 limit, uint256 legCount);
    error ComboBasketConditionNotPrepared(uint256 fullNoPositionId, uint256 index, bytes32 conditionId);
    error ComboMarketAlreadyExists(bytes32 marketId);
    error ComboMarketNotFound(bytes32 marketId);
    error ComboMarketInvalidPosition(address positionToken, uint256 positionId);
}
