[profile.default]
src = "../conditional-tokens/contracts"
out = "../out/conditional-tokens"
libs = ["../lib"]
cache_path = "../cache/conditional-tokens"
solc_version = "0.5.17"
evm_version = "istanbul"
optimizer = false
remappings = [
    "openzeppelin-solidity/=../lib/openzeppelin-solidity/",
]
